# Generated by Django 3.0.5 on 2020-04-25 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignTask',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('34adbed2-ec05-4524-9d5f-f859c9af1183'), primary_key=True, serialize=False, verbose_name='UUID')),
                ('title', models.CharField(max_length=20, verbose_name='任务名')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('stop', models.BooleanField(default=False, verbose_name='状态')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
        ),
        migrations.CreateModel(
            name='SignLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=30, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('sign_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SignIn.SignTask', verbose_name='签到任务')),
            ],
        ),
    ]
